### ISSUE TITLE
Rebase do doxyparse com o upstream do doxygen

### ISSUE THREAD

**Issue by iamferreirajp** [analizo-mes/analizo#3]
O suporte a python foi possivelmente implementado de acordo com a documentação das releases mais recentes do Doxygen (investigar). Para o Analizo prover suporte a Python, o Doxyparse precisa incluir essas alterações.

**Comment by arkye** [comment]
Issue finalizada. Confere @joenio e @luanguimaraesla ?

**Comment by joenio** [comment]
precisamos investigar os testes do analizo com a versão do doxyparse "rebaseada", o doxyparse atualizado com o master do doxygen é este aqui:

* https://github.com/analizo/doxyparse/tree/rebase-upstream-master

tem testes do analizo falhando com essa "nova" versão, precisamos corrigir esses testes.

**Comment by arkye** [comment]
Vou criar uma nova issue com esses requisitos. Terminando lá, terminamos aqui.
