### ISSUE TITLE
Remover código YAML

### ISSUE THREAD

**Issue by marcelohpf** [analizo-mes/analizo#36]
Remover código de geração do YAML e trocar por uma biblioteca

**Comment by VinyPinheiro** [comment]
Atualmente a saída do doxyparse não está seguindo o padrão YAML. Toda a saida teria que ser reformatada

**Comment by VinyPinheiro** [comment]
Atualmente o doxyparse retorna:

file /home/vinicius/Documentos/UNB/Semestres/8/MES/past/analizo/t/samples/hello_world/c/hello_world.c
module hello_world.c
   variable hello_world_id in line 6
      protection public
   function hello_world_new() in line 8
      protection public
      5 lines of code
      0 parameters
      1 conditional paths
      uses variable hello_world_id defined in hello_world.c
   function hello_world_say(hello_world *) in line 14
      protection public
      3 lines of code
      1 parameters
      1 conditional paths
   function hello_world_destroy(hello_world *) in line 18
      protection public
      4 lines of code
      1 parameters
      1 conditional paths

Esses dados em um YAML poderiam ficar assim (Uma sugestão):
--- 
file: /home/vinicius/Documentos/UNB/Semestres/8/MES/past/analizo/t/samples/hello_world/c/hello_world.c
module: 
  file_name: hello_world.c
  metadata: 
    ? "variable hello_world_id in line 6"
    :
      - protection public
    ? "function hello_world_new() in line 8"
    :
      - protection public
      - "5 lines of code"
      - "0 parameters"
      - "1 conditional paths"
      - "uses variable id defined in _hello_world"
      - "uses variable hello_world_id defined in hello_world.c"
    ? "function hello_world_say(hello_world *) in line 14"
    :
      - protection public
      - "3 lines of code"
      - "1 parameters"
      - "1 conditional paths"
      - "uses variable id defined in _hello_world"
    ? "function hello_world_destroy(hello_world *) in line 18"
    :
      - protection public
      - "4 lines of code"
      - "1 parameters"
      - "1 conditional paths"
      - "uses variable id defined in _hello_world"
...

**Comment by VinyPinheiro** [comment]
O doxyparse retorna:
![image](https://user-images.githubusercontent.com/7025674/30568207-4c44d488-9caa-11e7-87ba-551a53da47de.png)
Uma sugestão de YAML válido:
![image](https://user-images.githubusercontent.com/7025674/30568227-64c56dd8-9caa-11e7-99d8-4b7beed79cf5.png)
