### ISSUE TITLE
Criar arquivo de configuracao para a saida default do calculo de metrica

### ISSUE THREAD

**Issue by LeonardoRk** [analizo-mes/analizo#42]
Em vez de exibir a média de cada métrica, exibir um default ou o de acordo com o configurado em algum arquivo de configuração (customizável)

**Comment by joenio** [comment]
pode ser através de parâmetro de linha de comando também ao invés de arquivo de configuração, o analizo já possui suporte para configurar parametros default de linha de comando em um arquivo de configuração `.analizo`
