### ISSUE TITLE
Criar Analizo REST API

### ISSUE THREAD

**Issue by iamferreirajp** [analizo-mes/analizo#7]
Criar sistema para disponibilizar os recursos do Analizo via API REST

Um protótipo com esta ideia foi implementado tempos atras, talvez seja uma boa inspiração ou até mesmo um ponto de partida:

https://github.com/joenio/codejuicer

**Comment by luanguimaraesla** [comment]
Envolve um projeto nove e não se encaixa no contexto da matéria
